name: Update repository

on:
  workflow_dispatch:

jobs:
  update-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python 3.12.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update repository
        run: python update_repo.py

      - name: Generate repository
        run: python _repo_generator.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Updated repository with latest addons"
            git push
          fi
